name: Build SukiSU-Ultra for Noting Phone (3a)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2
      with:
        repository: NothingOSS/android_kernel_msm-6.1_nothing_sm7635
    - name: Preparements
      run: |
        ls
        pwd

        sudo apt install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache
        sudo apt install -y git gnupg flex bison gperf build-essential zip curl wget zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc

        echo "[+] Append kernel params to kprobes"
        echo "CONFIG_KPM=y" >> arch/arm64/configs/gki_defconfig

        echo "[+] Patch with SukiSU-Ultra"
        curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main

        echo "[+] Done."
    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        KERNEL_PATH: android_kernel_msm-6.1_nothing_sm7635
      with:
        arch: arm64
        compiler: proton-clang/master/binutils
        defconfig: gki_defconfig
        image: Image
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Image
        path: android_kernel_msm-6.1_nothing_sm7635/arch/arm64/boot/Image
        if-no-files-found: warn
        retention-days: 30

